version: '3'
services:
  starwar:
      build: .
      container_name: starwar
      ports:
        - 8080:80
      env_file:
        - ./.env
      tty: true
      volumes:
        - .:/src
        - .:/usr/src/app
        - ./bin/log/starwar:/var/log/application/starwar
  mysql:
    container_name: starwar_db
    image: mysql:5.7
    environment:
          # with mysql
          MYSQL_DATABASE: starwar
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./bin/data/mysql:/var/lib/mysql
    ports:
      - 37827:3306